### ISSUE TITLE
Cache file contents also in memory?

### ISSUE THREAD

**Issue by alexlawrence** [trello/node-coffee-cache#12]
Thanks for developing this module. Great piece of work! 

I have one question about caching in memory.

Consider the following scenario: We are running a lot of tests and before _each_ of these tests we clear the complete require cache of NodeJS to guarantee an isolated testing environment without any previous state. 

This module helps in improving the performance drastically. However, I think it could be even faster if we used in memory caching. For our use case it wouldn´t even be required that the compiled results are written to the disk. 

Do you think it makes sense to extend this module so it can optionally also cache the results in memory? If yes, I can provide a pull request.

**Comment by dpatti** [comment]
I don't think it's a crazy idea, but on the other hand, that would make coffee files behave specially. I think my first instinct is to do the functionality you want in a separate module that provides in-memory caching for _all_ require extensions, and by loading that module and this in the right order, you get the best of both worlds. I assume this would be better for you anyway since you get in-memory caching for your node_modules too.

What do you think? My guess is that there isn't serious code in this library that would make an extension much easier than a new module.

**Comment by alexlawrence** [comment]
I understand and agree. 

We measured the performance and caching the file system operations isn´t anywhere near the improvement we get from caching the CoffeeScript compilation step. We will try to cache file system reads in general but that´s just a nice to have :-) . 

Currently testing this one: https://github.com/papandreou/node-cachedfs

**Comment by dpatti** [comment]
I'll leave this feature to another module, then. Thanks for the discussion!
